### Register User ###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "ishida@example.com",
  "password": "soulreaper"
}

###

### Login User ###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "ichigo@example.com",
  "password": "soulreaper"
}

###
